Week3
FreeCourseJava/dagestan1_example1 pull request #5
Opened 2022-07-05 19:10 UTC by dagestan1

долго боролся с гитом и idea, (переустанавливал винду и все делал по новой), было лишних коммитов, сильно не бейте

2022-07-05 19:22 UTC, hyragano requested changes

2022-07-05 19:22 UTC, hyragano commented on src/main/java/week3/week3_second.java
> +                    int plus = date[j+1];
что означает переменная  plus? 
 Переименуй лучше, другой будет читать, не поймет что к чему

2022-07-05 19:22 UTC, hyragano commented on src/main/java/week3/week3_second.java
> +        for (int i = 0; i < date.length-1; i++) {
сортировку нужно вынести в метод.

2022-07-05 19:22 UTC, hyragano commented on src/main/java/week3/week3_third.java
> +        for (int i = 0; i < date.length - 1; i++) {
Тут уже можно будет вызывать метод из второго задания

2022-07-05 19:40 UTC, blekkiw requested changes

2022-07-05 19:40 UTC, blekkiw commented on src/main/java/week3/week3_first.java
> +public class week3_first {
CamelCase

2022-07-06 14:37 UTC, dagestan1 commented on src/main/java/week3/week3_first.java
> +public class week3_first {
> CamelCase

а в чем именно? подскажите пожалуйста

2022-07-06 14:44 UTC, blekkiw commented on src/main/java/week3/week3_first.java
> +public class week3_first {
Название класса должно быть ThirdWeek или WeekThree. Без подчеркиваний

2022-07-06 15:11 UTC, dagestan1 commented on src/main/java/week3/week3_first.java
> +public class week3_first {
> Название класса должно быть ThirdWeek или WeekThree. Без подчеркиваний

принял, спасибо

2022-07-07 21:37 UTC, hyragano requested changes

2022-07-07 21:37 UTC, hyragano commented on src/main/java/week3/third.java
> +            for (int i = 0; i < date.length - 1; i++) {
Нужно было сделать копию и вернуть другой массив, который уже отсортирован. Если есть время, то лучше так сделать

2022-08-05 14:00 UTC, hyragano approved these changes

2022-08-21 16:38 UTC, merged