задания 4 дня, жду комментариев(перезалив)
FreeCourseJava/dagestan1_example1 pull request #6
Opened 2022-07-09 17:56 UTC by dagestan1

2022-07-09 18:14 UTC, hyragano requested changes

2022-07-09 18:14 UTC, hyragano commented on src/main/java/week4/first.java
> +        } while (left <= right);
По классике разве тут не другая проверка?

2022-07-09 18:14 UTC, hyragano commented on src/main/java/week4/second.java
> +                return binarySearch(date, example, low, middle - 1);
Можно свести все к одному вызову binarySearch в конце

2022-07-13 13:52 UTC, blekkiw requested changes

2022-07-13 13:52 UTC, blekkiw commented on src/main/java/week4/first.java
> +public class first {
CamelCase

2022-07-13 13:52 UTC, blekkiw commented on src/main/java/week4/first.java
> +        int right = array1.length- 1;
Крайне странно видеть тут это выражение. Оно никак не относится к этому куску кода. Лучше бы его переложить поближе к тому месту, где это используется

2022-07-13 13:52 UTC, blekkiw commented on src/main/java/week4/second.java
> +        System.out.println(binarySearch((dateSorted), 1937, low, hight));
Мне кажется, тут есть лишние скобки

2022-07-13 13:52 UTC, blekkiw commented on src/main/java/week4/second.java
> +        int hight = date.length-1;
Та же ерунда. Эти две переменные не имеют отношения к коду в этом блоке.

2022-07-13 13:52 UTC, blekkiw commented on src/main/java/week4/second.java
> +        int low =0;
Определись, либо ставишь пробелы между операторами, либо нет

2022-07-24 18:31 UTC, dagestan1 commented on src/main/java/week4/first.java
> +        int right = array1.length- 1;
> Крайне странно видеть тут это выражение. Оно никак не относится к этому куску кода. Лучше бы его переложить поближе к тому месту, где это используется

это же обозначение крайней границы, чет не понимаю, где оно ещё должно быть

2022-07-24 18:34 UTC, dagestan1 commented on src/main/java/week4/second.java
> +        int hight = date.length-1;
> Та же ерунда. Эти две переменные не имеют отношения к коду в этом блоке.

тут тоже самое, так и не понял, где эти переменные должны находиться

2022-07-24 18:59 UTC, blekkiw commented on src/main/java/week4/first.java
> +        int right = array1.length- 1;
Их совершенно точно можно спрятать в сортирующий метод

2022-07-25 19:42 UTC, dagestan1 commented on src/main/java/week4/first.java
> +        int right = array1.length- 1;
> Их совершенно точно можно спрятать в сортирующий метод

принял, спасибо

2022-08-03 09:22 UTC, dagestan1 commented on src/main/java/week4/first.java
> +        } while (left <= right);
> По классике разве тут не другая проверка?

не догоняю, эта не правильная? вроде все проверки проходит

2022-08-05 13:59 UTC, hyragano approved these changes

2022-08-05 14:11 UTC, merged